version: "3.8"

services:
    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1
            POSTGRES_DB: Todo
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    mongo:
        image: mongo:6
        restart: always
        ports:
            - "27018:27017"
        volumes:
            - mongodata:/data/db

    cmd-service:
        build:
            context: ./cmd-service
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=1
            - DB_NAME=Todo
        depends_on:
            - postgres

    query-service:
        build:
            context: ./query-service
        ports:
            - "8081:8080"
        environment:
            - MONGO_URI=mongodb://mongo:27017
        depends_on:
            - mongo

volumes:
    pgdata:
    mongodata:
